let jsonFile = {
    "Models" : [
        
        {
            "ModelId": 316,
            "ModelName": "نخودی و نسکافه ای",
            "ModelRef": "",
            "QtyRemaining": 1,
            "QtyStockSet": 1,
            "Description": "",
            "ColorId": -1,
            "ColorText": "",
            "ColorValue": "",
            "SizeId": 4,
            "SizeText": "FREE SIZE",
            "WeightId": -1,
            "WeightText": "",
            "WeightValue": "",
            "UnitCost": 9480001,
            "AfterDiscount": 948000,
            "DiscountPercent": 0,
            "DiscountAmount": 0,
            "DiscountStartDate": "",
            "DiscountEndDate": "",
            "IsSpecialDiscount": false,
            "VendorId": "0",
            "VendorName": "",
            "ImageUrl": "/Portals/0/productimages/78-03232IMG-20230714-022918-710.jpg",
            "Extra": ""
        },
        {
            "ModelId": 317,
            "ModelName": "کرمی و مشکی",
            "ModelRef": "",
            "QtyRemaining": 0,
            "QtyStockSet": 1,
            "Description": "",
            "ColorId": -1,
            "ColorText": "",
            "ColorValue": "",
            "SizeId": 4,
            "SizeText": "FREE SIZE",
            "WeightId": -1,
            "WeightText": "",
            "WeightValue": "",
            "UnitCost": 9480002,
            "AfterDiscount": 948000,
            "DiscountPercent": 0,
            "DiscountAmount": 0,
            "DiscountStartDate": "",
            "DiscountEndDate": "",
            "IsSpecialDiscount": false,
            "VendorId": "0",
            "VendorName": "",
            "ImageUrl": "/Portals/0/productimages/78-22463IMG-20230714-022918-201.jpg",
            "Extra": ""
        },
        {
            "ModelId": 318,
            "ModelName": "سبز و کرمی",
            "ModelRef": "",
            "QtyRemaining": 1,
            "QtyStockSet": 1,
            "Description": "",
            "ColorId": -1,
            "ColorText": "",
            "ColorValue": "",
            "SizeId": 4,
            "SizeText": "FREE SIZE",
            "WeightId": -1,
            "WeightText": "",
            "WeightValue": "",
            "UnitCost": 9480003,
            "AfterDiscount": 948000,
            "DiscountPercent": 0,
            "DiscountAmount": 0,
            "DiscountStartDate": "",
            "DiscountEndDate": "",
            "IsSpecialDiscount": false,
            "VendorId": "0",
            "VendorName": "",
            "ImageUrl": "/Portals/0/productimages/78-428edIMG-20230714-022918-301.jpg",
            "Extra": ""
        },
        {
            "ModelId": 319,
            "ModelName": "نخودی و سبز",
            "ModelRef": "",
            "QtyRemaining": 1,
            "QtyStockSet": 1,
            "Description": "",
            "ColorId": -1,
            "ColorText": "",
            "ColorValue": "",
            "SizeId": 4,
            "SizeText": "FREE SIZE",
            "WeightId": -1,
            "WeightText": "",
            "WeightValue": "",
            "UnitCost": 9480004,
            "AfterDiscount": 948000,
            "DiscountPercent": 0,
            "DiscountAmount": 0,
            "DiscountStartDate": "",
            "DiscountEndDate": "",
            "IsSpecialDiscount": false,
            "VendorId": "0",
            "VendorName": "",
            "ImageUrl": "/Portals/0/productimages/78-69a11IMG-20230714-022918-166.jpg",
            "Extra": ""
        }
    ]
    
}